# Single always-on VM for archive-wiki-api: a small stateless-ish HTTP+MCP
# service over the (private) bkc-archive-wiki repo — see that repo's
# api/README.md. Not a MIG/autoscaler for the same reason chroma-vm isn't:
# one low-traffic Node process, no cluster to scale. Unlike chroma-vm/
# mongo-vm, there's no separate attached data disk — everything this VM
# needs (the git checkout, node_modules, build output, and the one thing it
# writes at runtime) fits fine on the boot disk, and none of it is data this
# infra needs to snapshot: the wiki content is already durable in git, and
# an unreviewed draft conversation lost between backups is a curator
# re-filing it, not a rebuild-from-scratch cost the way Chroma's index is.
#
# Runs archive-wiki-api directly under systemd (no Docker): the app has no
# published container image (unlike Chroma/Mongo, which are pulling
# existing public images), so replicating its own documented native
# deployment (git clone, npm ci && npm run build, systemd unit, a cron for
# git-pull-and-reindex — see api/README.md) is less to build and maintain
# than inventing a Dockerfile and an image-build pipeline for it.

# Generated by Terraform, never typed by hand, never in git — same
# tradeoff as mongo-vm's random_password (lands in Terraform state). Gates
# every route except GET /v1/health once this is reachable off a public
# domain (see manual-setup-checklist.md item 5) — the app runs
# unauthenticated when this is unset, which is fine for local dev, not for
# a public LB backend.
resource "random_password" "archive_api_token" {
  length  = 32
  special = false
}

# Stored for llm_engine's web-server tier to read once it's wired to call
# this service (ARCHIVE_API_URL/ARCHIVE_API_TOKEN — see
# manual-setup-checklist.md item 5); not consumed by anything yet. Same
# user_managed replication shape as mongo-vm's mongodb_url secret — see
# atlas-cluster/main.tf for the org-policy constraint behind that.
resource "google_secret_manager_secret" "archive_api_token" {
  project   = var.project_id
  secret_id = var.archive_api_token_secret_name
  labels    = merge(var.labels, { component = "archive-wiki-vm" })

  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }
}

resource "google_secret_manager_secret_version" "archive_api_token" {
  secret      = google_secret_manager_secret.archive_api_token.id
  secret_data = random_password.archive_api_token.result
}

# Not created by this module — see deploy_key_secret_name's description for
# why (no github provider here) and manual-setup-checklist.md for the
# one-time setup. Read as a data source purely so its value can be baked
# into the startup script below, the same way mongo-vm bakes its generated
# DB password in rather than having the VM fetch a secret at boot.
data "google_secret_manager_secret_version" "deploy_key" {
  secret = var.deploy_key_secret_name
}

# Dedicated service account for the Ops Agent (CPU/memory/disk metrics —
# see monitoring module). Without this the instance runs with NO service
# account at all — google_compute_instance, unlike `gcloud compute
# instances create`, does not implicitly attach the project's default
# Compute Engine service account when the service_account block is omitted
# (see chroma-vm/mongo-vm's own comments on this, confirmed live against
# both). Deliberately has no Secret Manager IAM grant: both secrets above
# are read by Terraform itself (a data source, and a resource this module
# owns), not by the VM at runtime.
resource "google_service_account" "archive_wiki_vm" {
  project      = var.project_id
  account_id   = "llm-engine-archive-wiki-vm"
  display_name = "llm_engine archive-wiki-vm (Ops Agent)"
}

resource "google_project_iam_member" "archive_wiki_vm_log_writer" {
  project = var.project_id
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.archive_wiki_vm.email}"
}

resource "google_project_iam_member" "archive_wiki_vm_metric_writer" {
  project = var.project_id
  role    = "roles/monitoring.metricWriter"
  member  = "serviceAccount:${google_service_account.archive_wiki_vm.email}"
}

resource "google_compute_instance" "archive_wiki" {
  project      = var.project_id
  name         = "llm-engine-archive-wiki-vm"
  zone         = var.zone
  machine_type = var.machine_type
  tags         = [var.network_tag, var.iap_ssh_tag]
  labels       = merge(var.labels, { component = "archive-wiki-vm" })

  boot_disk {
    initialize_params {
      image = var.boot_disk_image
      size  = var.boot_disk_size_gb
      type  = "pd-balanced"
    }
  }

  network_interface {
    subnetwork = var.subnet_self_link
    # No access_config block: intentionally no external IP. Reachable only
    # via the LB (through the NEG/backend service below) and, for admin
    # access, IAP SSH tunneling.
  }

  service_account {
    email  = google_service_account.archive_wiki_vm.email
    scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }

  metadata = {
    startup-script = templatefile("${path.module}/startup-script.sh.tpl", {
      archive_api_port  = var.archive_api_port
      archive_api_token = random_password.archive_api_token.result
      deploy_key        = data.google_secret_manager_secret_version.deploy_key.secret_data
    })
  }

  # Stateful singleton with an in-place boot disk (git checkout + any
  # unreviewed drafts on it) — stop/start in place on a change that would
  # otherwise force recreation, same as chroma-vm/mongo-vm. A
  # startup-script metadata change only re-runs on the *next* boot; reset
  # the instance if you need it sooner
  # (`gcloud compute instances reset llm-engine-archive-wiki-vm`).
  allow_stopping_for_update = true
}

# --- LB backend: a zonal NEG pointed straight at this one VM+port, since
#     it's a standalone instance, not a MIG. See webserver-mig's
#     extra_host_backends variable for how this plugs into the shared LB. ---

resource "google_compute_network_endpoint_group" "archive_wiki" {
  project               = var.project_id
  name                  = "llm-engine-archive-wiki-neg"
  network_endpoint_type = "GCE_VM_IP_PORT"
  zone                  = var.zone
  network               = var.network_self_link
  subnetwork            = var.subnet_self_link
  default_port          = var.archive_api_port
}

resource "google_compute_network_endpoint" "archive_wiki" {
  network_endpoint_group = google_compute_network_endpoint_group.archive_wiki.id
  # Not inferred from network_endpoint_group above despite the two sharing
  # the same NEG id — the provider errors "zone: required field is not
  # set" at plan time without this explicit, discovered wiring
  # archive-wiki-vm into infra/environments/prod for the first time
  # (llm_engine-infra's manual-setup-checklist.md item 5) in a project with
  # no provider-level default zone.
  zone       = var.zone
  instance   = google_compute_instance.archive_wiki.name
  ip_address = google_compute_instance.archive_wiki.network_interface[0].network_ip
  port       = var.archive_api_port
}

resource "google_compute_health_check" "archive_wiki" {
  project = var.project_id
  name    = "llm-engine-archive-wiki-health-check"

  http_health_check {
    port         = var.archive_api_port
    request_path = "/v1/health" # unauthenticated even when ARCHIVE_API_TOKEN is set — see app.ts
  }
}

resource "google_compute_backend_service" "archive_wiki" {
  project               = var.project_id
  name                  = "llm-engine-archive-wiki-backend"
  protocol              = "HTTP"
  load_balancing_scheme = "EXTERNAL_MANAGED"
  timeout_sec           = 30
  health_checks         = [google_compute_health_check.archive_wiki.id]

  backend {
    group                 = google_compute_network_endpoint_group.archive_wiki.id
    balancing_mode        = "RATE"
    max_rate_per_endpoint = 50 # one small VM behind this — a low ceiling is the point, not a limit anyone should expect to hit
  }
}
