# Single standalone MongoDB VM — the low-budget fallback for the
# atlas-cluster module, for when Atlas isn't an option (e.g. no permission
# yet to activate the GCP Marketplace subscription atlas-cluster assumes).
# Same shape as chroma-vm: a fixed singleton with its own persistent data
# disk, not a MIG — there's no cluster to autoscale here.
#
# Deliberately NOT a replica set: llm_engine doesn't use multi-document
# transactions or change streams, so a standalone mongod is sufficient and
# a lot less operational overhead than a single-node replica set (keyfile
# auth between members, oplog sizing, etc. for no benefit).
#
# Not wired into any environment by default, and not meant to run
# alongside atlas-cluster — pick one or the other in your own
# environments/ config. Both modules default to writing the same Secret
# Manager secret name (llm-engine-mongodb-url), so webserver-mig's
# mongodb_url_secret_id wiring doesn't need to change when switching.

resource "google_compute_disk" "mongo_data" {
  project = var.project_id
  name    = "llm-engine-mongo-data"
  zone    = var.zone
  type    = var.data_disk_type
  size    = var.data_disk_size_gb
  labels  = merge(var.labels, { component = "mongo-vm" })
}

# Generated by Terraform, never typed by hand, never in git — same
# tradeoff as atlas-cluster's random_password (lands in Terraform state).

resource "random_password" "app_db_user" {
  length  = 32
  special = false # no symbols: avoids URL-encoding in the mongodb:// URI and quoting issues in the startup script
}

resource "random_password" "root_user" {
  length  = 32
  special = false
}

resource "google_compute_instance" "mongo" {
  project      = var.project_id
  name         = "llm-engine-mongo-vm"
  zone         = var.zone
  machine_type = var.machine_type
  tags         = [var.network_tag, var.iap_ssh_tag]
  labels       = merge(var.labels, { component = "mongo-vm" })

  boot_disk {
    initialize_params {
      image = var.boot_disk_image
      size  = var.boot_disk_size_gb
      type  = "pd-balanced"
    }
  }

  attached_disk {
    source      = google_compute_disk.mongo_data.self_link
    device_name = "mongo-data"
  }

  network_interface {
    subnetwork = var.subnet_self_link
    # No access_config block: intentionally no external IP, same as
    # chroma-vm. Reachable only from inside the VPC — the network module's
    # firewall further restricts it to web-server-tagged instances — and
    # administratively only via IAP SSH tunneling.
  }

  metadata = {
    startup-script = templatefile("${path.module}/startup-script.sh.tpl", {
      mongo_image           = var.mongo_image
      mongo_port            = var.mongo_port
      root_username         = var.root_username
      root_password         = random_password.root_user.result
      app_database_name     = var.app_database_name
      app_db_username       = var.app_db_username
      app_db_password       = random_password.app_db_user.result
      wiredtiger_cache_gb   = var.wiredtiger_cache_size_gb
      backup_hour_utc       = var.backup_hour_utc
      backup_retention_days = var.backup_retention_days
    })
  }

  # This VM is a stateful singleton with an in-place data disk. Changes
  # that would normally force recreation (machine_type, etc.) instead
  # stop/start it in place so the attached data disk survives. Note: a
  # startup-script metadata change only re-runs on the *next* boot —
  # apply, then reset the instance (`gcloud compute instances reset
  # llm-engine-mongo-vm`) if you need it to take effect immediately rather
  # than at its next natural restart. The init script that creates the app
  # user only runs once anyway (against an empty data directory), so a
  # reset after the first boot won't touch existing users/data.
  allow_stopping_for_update = true
}

# --- Scheduled disk snapshot (disk-snapshot-policy module — the same
# strategy every stateful disk in this infra uses, see chroma-vm for the
# other caller), staggered *after* the mongodump cron job
# (startup-script.sh.tpl) so each day's snapshot is taken once that day's
# dump is reliably done — the snapshot then covers both the live data
# files and the dump archives sitting next to them on the same disk. This
# is a second, independent line of recovery on top of the mongodump
# archives themselves (e.g. disk corruption a mongodump wouldn't catch),
# not a replacement for them.

module "data_disk_snapshot" {
  source = "../disk-snapshot-policy"

  project_id        = var.project_id
  region            = var.region
  zone              = var.zone
  disk_name         = google_compute_disk.mongo_data.name
  policy_name       = "llm-engine-mongo-data-snapshot"
  snapshot_hour_utc = var.snapshot_hour_utc
  retention_days    = var.snapshot_retention_days
  labels            = merge(var.labels, { component = "mongo-vm" })
}

# --- Connection string, stored in Secret Manager, never in state output text ---
# Same secret_id default and shape as atlas-cluster's output, so
# webserver-mig's mongodb_url_secret_id wiring is a drop-in swap.

resource "google_secret_manager_secret" "mongodb_url" {
  project   = var.project_id
  secret_id = var.mongodb_url_secret_name
  labels    = merge(var.labels, { component = "mongo-vm" })

  # See atlas-cluster/main.tf for why this is user_managed, not auto —
  # same org-policy constraint applies here.
  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }
}

resource "google_secret_manager_secret_version" "mongodb_url" {
  secret = google_secret_manager_secret.mongodb_url.id
  # retryWrites=false is deliberate, not an oversight: retryable writes
  # require a replica set or mongos, and this is a standalone mongod — the
  # driver rejects writes with retryWrites=true (or the default omitted)
  # against a standalone deployment.
  secret_data = format(
    "mongodb://%s:%s@%s:%s/%s?authSource=admin&retryWrites=false",
    var.app_db_username,
    random_password.app_db_user.result,
    google_compute_instance.mongo.network_interface[0].network_ip,
    var.mongo_port,
    var.app_database_name
  )
}
