# Single standalone MongoDB VM — the low-budget fallback for the
# atlas-cluster module, for when Atlas isn't an option (e.g. no permission
# yet to activate the GCP Marketplace subscription atlas-cluster assumes).
# Same shape as chroma-vm: a fixed singleton with its own persistent data
# disk, not a MIG — there's no cluster to autoscale here.
#
# Deliberately NOT a replica set: llm_engine doesn't use multi-document
# transactions or change streams, so a standalone mongod is sufficient and
# a lot less operational overhead than a single-node replica set (keyfile
# auth between members, oplog sizing, etc. for no benefit).
#
# Not wired into any environment by default, and not meant to run
# alongside atlas-cluster — pick one or the other in your own
# environments/ config. Both modules default to writing the same Secret
# Manager secret name (llm-engine-mongodb-url), so webserver-mig's
# mongodb_url_secret_id wiring doesn't need to change when switching.

resource "google_compute_disk" "mongo_data" {
  project = var.project_id
  name    = "llm-engine-mongo-data"
  zone    = var.zone
  type    = var.data_disk_type
  size    = var.data_disk_size_gb
  labels  = merge(var.labels, { component = "mongo-vm" })

  # This is the system of record when running without Atlas — protect it
  # from an accidental `terraform destroy`/replace. A data_disk_type change
  # (see that variable's description) still forces a replace regardless of
  # this; snapshot the disk first if you ever need to change it.
  lifecycle {
    prevent_destroy = true
  }
}

# Generated by Terraform, never typed by hand, never in git — same
# tradeoff as atlas-cluster's random_password (lands in Terraform state).
# Rotating either password afterward isn't a `terraform apply` — the
# startup script only ever runs createUser/MONGO_INITDB_ROOT_PASSWORD
# against an empty data directory (see the init script comment below), so
# rotation needs a manual `db.changeUserPassword(...)` (or the root
# equivalent) over an IAP-tunneled mongosh session, followed by updating
# the corresponding Secret Manager secret version by hand.

resource "random_password" "app_db_user" {
  length  = 32
  special = false # no symbols: avoids URL-encoding in the mongodb:// URI and quoting issues in the startup script
}

resource "random_password" "root_user" {
  length  = 32
  special = false
}

# Both passwords are handed to the VM only as Secret Manager secret IDs
# (metadata below) — never rendered into the startup-script text itself.
# Instance metadata is readable by anyone with compute.instances.get on
# this project (e.g. `gcloud compute instances describe`) and by any
# process running on the VM, so a plaintext password there is effectively
# not a secret. The startup script fetches the actual values at boot via
# the instance's own service account credentials (metadata-server OAuth
# token + Secret Manager REST API), which only the two
# google_secret_manager_secret_iam_member grants below allow it to do.

resource "google_secret_manager_secret" "mongo_root_password" {
  project   = var.project_id
  secret_id = "llm-engine-mongo-vm-root-password"
  labels    = merge(var.labels, { component = "mongo-vm" })

  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }
}

resource "google_secret_manager_secret_version" "mongo_root_password" {
  secret      = google_secret_manager_secret.mongo_root_password.id
  secret_data = random_password.root_user.result
}

resource "google_secret_manager_secret" "mongo_app_db_password" {
  project   = var.project_id
  secret_id = "llm-engine-mongo-vm-app-db-password"
  labels    = merge(var.labels, { component = "mongo-vm" })

  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }
}

resource "google_secret_manager_secret_version" "mongo_app_db_password" {
  secret      = google_secret_manager_secret.mongo_app_db_password.id
  secret_data = random_password.app_db_user.result
}

resource "google_secret_manager_secret_iam_member" "mongo_vm_root_password_accessor" {
  project   = var.project_id
  secret_id = google_secret_manager_secret.mongo_root_password.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.mongo_vm.email}"
}

resource "google_secret_manager_secret_iam_member" "mongo_vm_app_db_password_accessor" {
  project   = var.project_id
  secret_id = google_secret_manager_secret.mongo_app_db_password.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.mongo_vm.email}"
}

# Dedicated service account for the Ops Agent (CPU/memory/disk metrics —
# see monitoring module) and the backup cron's status log lines. Without
# this, the instance runs with NO service account at all — Terraform's
# google_compute_instance, unlike `gcloud compute instances create`, does
# not implicitly attach the project's default Compute Engine service
# account when the service_account block is omitted (confirmed live via
# `gcloud compute instances describe ... --format='yaml(serviceAccounts)'`
# returning null), so neither the Ops Agent nor a `gcloud logging write`
# could ever have authenticated. Mirrors webserver-mig's own dedicated-SA
# pattern.
resource "google_service_account" "mongo_vm" {
  project      = var.project_id
  account_id   = "llm-engine-mongo-vm"
  display_name = "llm_engine mongo-vm (Ops Agent + backup logging)"
}

resource "google_project_iam_member" "mongo_vm_log_writer" {
  project = var.project_id
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.mongo_vm.email}"
}

resource "google_project_iam_member" "mongo_vm_metric_writer" {
  project = var.project_id
  role    = "roles/monitoring.metricWriter"
  member  = "serviceAccount:${google_service_account.mongo_vm.email}"
}

resource "google_compute_instance" "mongo" {
  project      = var.project_id
  name         = "llm-engine-mongo-vm"
  zone         = var.zone
  machine_type = var.machine_type
  tags         = [var.network_tag, var.iap_ssh_tag]
  labels       = merge(var.labels, { component = "mongo-vm" })

  boot_disk {
    initialize_params {
      image = var.boot_disk_image
      size  = var.boot_disk_size_gb
      type  = "pd-balanced"
    }
  }

  attached_disk {
    source      = google_compute_disk.mongo_data.self_link
    device_name = "mongo-data"
  }

  network_interface {
    subnetwork = var.subnet_self_link
    # No access_config block: intentionally no external IP, same as
    # chroma-vm. Reachable only from inside the VPC — the network module's
    # firewall further restricts it to web-server-tagged instances — and
    # administratively only via IAP SSH tunneling.
  }

  service_account {
    email  = google_service_account.mongo_vm.email
    scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }

  # Wait for the SA's secretAccessor grants before first boot — otherwise
  # the startup script's Secret Manager fetch can lose the race against IAM
  # propagation and fail on the very first boot.
  depends_on = [
    google_secret_manager_secret_iam_member.mongo_vm_root_password_accessor,
    google_secret_manager_secret_iam_member.mongo_vm_app_db_password_accessor,
  ]

  metadata = {
    startup-script = templatefile("${path.module}/startup-script.sh.tpl", {
      gcp_project_id            = var.project_id
      mongo_image               = var.mongo_image
      mongo_port                = var.mongo_port
      root_username             = var.root_username
      root_password_secret_id   = google_secret_manager_secret.mongo_root_password.secret_id
      app_database_name         = var.app_database_name
      app_db_username           = var.app_db_username
      app_db_password_secret_id = google_secret_manager_secret.mongo_app_db_password.secret_id
      wiredtiger_cache_gb       = var.wiredtiger_cache_size_gb
      backup_hour_utc           = var.backup_hour_utc
      backup_retention_days     = var.backup_retention_days
    })
  }

  # This VM is a stateful singleton with an in-place data disk. Changes
  # that would normally force recreation (machine_type, etc.) instead
  # stop/start it in place so the attached data disk survives. Note: a
  # startup-script metadata change only re-runs on the *next* boot —
  # apply, then reset the instance (`gcloud compute instances reset
  # llm-engine-mongo-vm`) if you need it to take effect immediately rather
  # than at its next natural restart. The init script that creates the app
  # user only runs once anyway (against an empty data directory), so a
  # reset after the first boot won't touch existing users/data.
  allow_stopping_for_update = true
}

# --- Scheduled disk snapshot (disk-snapshot-policy module — the same
# strategy every stateful disk in this infra uses, see chroma-vm for the
# other caller), staggered *after* the mongodump cron job
# (startup-script.sh.tpl) so each day's snapshot is taken once that day's
# dump is reliably done — the snapshot then covers both the live data
# files and the dump archives sitting next to them on the same disk. This
# is a second, independent line of recovery on top of the mongodump
# archives themselves (e.g. disk corruption a mongodump wouldn't catch),
# not a replacement for them.

module "data_disk_snapshot" {
  source = "../disk-snapshot-policy"

  project_id        = var.project_id
  region            = var.region
  zone              = var.zone
  disk_name         = google_compute_disk.mongo_data.name
  policy_name       = "llm-engine-mongo-data-snapshot"
  snapshot_hour_utc = var.snapshot_hour_utc
  retention_days    = var.snapshot_retention_days
  labels            = merge(var.labels, { component = "mongo-vm" })
}

# --- Connection string, stored in Secret Manager, never in state output text ---
# Same secret_id default and shape as atlas-cluster's output, so
# webserver-mig's mongodb_url_secret_id wiring is a drop-in swap.

resource "google_secret_manager_secret" "mongodb_url" {
  project   = var.project_id
  secret_id = var.mongodb_url_secret_name
  labels    = merge(var.labels, { component = "mongo-vm" })

  # See atlas-cluster/main.tf for why this is user_managed, not auto —
  # same org-policy constraint applies here.
  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }
}

resource "google_secret_manager_secret_version" "mongodb_url" {
  secret = google_secret_manager_secret.mongodb_url.id
  # retryWrites=false is deliberate, not an oversight: retryable writes
  # require a replica set or mongos, and this is a standalone mongod — the
  # driver rejects writes with retryWrites=true (or the default omitted)
  # against a standalone deployment.
  #
  # authSource must be app_database_name, not "admin": the init script
  # (startup-script.sh.tpl) creates app_db_username via
  # db.getSiblingDB(app_database_name).createUser(...), which makes
  # app_database_name that user's authentication database, not admin — only
  # root_username (MONGO_INITDB_ROOT_USERNAME) lives in admin. authSource=admin
  # here would make every connection attempt fail with UserNotFound.
  secret_data = format(
    "mongodb://%s:%s@%s:%s/%s?authSource=%s&retryWrites=false",
    var.app_db_username,
    random_password.app_db_user.result,
    google_compute_instance.mongo.network_interface[0].network_ip,
    var.mongo_port,
    var.app_database_name,
    var.app_database_name
  )
}
