# MongoDB Atlas cluster + database user + VPC peering + backup policy
# (module B2). Uses mongodbatlas_advanced_cluster (mongodbatlas_cluster is
# deprecated) on the provider's current attribute-list schema (v2.x) —
# replication_specs/region_configs/electable_specs/auto_scaling are typed
# object literals assigned with `=`, not repeated `{}` blocks.
#
# Does NOT create a mongodbatlas_project — that already exists from the GCP
# Marketplace activation (manual-setup-checklist.md item 1); this module
# only manages resources inside it.

resource "mongodbatlas_advanced_cluster" "this" {
  project_id     = var.atlas_project_id
  name           = var.cluster_name
  cluster_type   = "REPLICASET"
  backup_enabled = true

  replication_specs = [{
    region_configs = [{
      provider_name = "GCP"
      region_name   = var.atlas_region_name
      priority      = 7

      electable_specs = {
        instance_size = var.instance_size
        node_count    = var.node_count
      }

      auto_scaling = {
        compute_enabled            = var.compute_autoscaling_enabled
        compute_scale_down_enabled = true
        compute_min_instance_size  = var.instance_size
        compute_max_instance_size  = var.compute_max_instance_size
        disk_gb_enabled            = var.disk_gb_autoscaling_enabled
      }
    }]
  }]
}

# --- Database user, least-privilege: readWrite on the app's database only ---
# Password generated by Terraform, never typed by hand, never in git. It
# does land in Terraform state (Infra Manager's own bucket) via
# random_password — see the comment on that resource for the tradeoff.

resource "random_password" "app_db_user" {
  length  = 32
  special = false # avoid characters that would need URL-encoding in a mongodb+srv:// URI
}

resource "mongodbatlas_database_user" "app" {
  project_id         = var.atlas_project_id
  username           = var.app_db_username
  password           = random_password.app_db_user.result
  auth_database_name = "admin"

  roles {
    role_name     = "readWrite"
    database_name = var.app_database_name
  }

  scopes {
    name = mongodbatlas_advanced_cluster.this.name
    type = "CLUSTER"
  }
}

# --- VPC peering: Atlas container + peering request, then the GCP-side accept ---
# Order matters: container before peering (container_id dependency below).

resource "mongodbatlas_network_container" "gcp" {
  project_id       = var.atlas_project_id
  atlas_cidr_block = var.atlas_cidr_block
  provider_name    = "GCP"
}

resource "mongodbatlas_network_peering" "gcp" {
  project_id     = var.atlas_project_id
  container_id   = mongodbatlas_network_container.gcp.container_id
  provider_name  = "GCP"
  gcp_project_id = var.gcp_project_id
  network_name   = var.gcp_network_name
}

resource "google_compute_network_peering" "atlas" {
  name         = "llm-engine-atlas-peering"
  network      = var.gcp_network_self_link
  peer_network = "https://www.googleapis.com/compute/v1/projects/${mongodbatlas_network_peering.gcp.atlas_gcp_project_id}/global/networks/${mongodbatlas_network_peering.gcp.atlas_vpc_name}"
}

# Atlas enforces its project IP access list independently of the peering
# connection above — a peered VPC's traffic still gets refused unless its
# CIDR is also listed here. See
# https://www.mongodb.com/docs/atlas/security-vpc-peering/ ("You must add
# the peered VPC's CIDR block to the project's IP access list").
resource "mongodbatlas_project_ip_access_list" "gcp_peered_vpc" {
  project_id = var.atlas_project_id
  cidr_block = var.gcp_vpc_cidr_block
  comment    = "GCP VPC peered via mongodbatlas_network_peering.gcp"
}

# --- Backup policy ---

resource "mongodbatlas_cloud_backup_schedule" "this" {
  project_id            = var.atlas_project_id
  cluster_name          = mongodbatlas_advanced_cluster.this.name
  reference_hour_of_day = var.backup_reference_hour_of_day

  policy_item_daily {
    frequency_interval = 1
    retention_unit     = "days"
    retention_value    = var.backup_daily_retention_days
  }

  policy_item_weekly {
    frequency_interval = 6 # Saturday — adjust freely, arbitrary choice
    retention_unit     = "weeks"
    retention_value    = var.backup_weekly_retention_weeks
  }

  depends_on = [mongodbatlas_advanced_cluster.this]
}

# --- Connection string, stored in Secret Manager, never in state output text ---

resource "google_secret_manager_secret" "mongodb_url" {
  project   = var.gcp_project_id
  secret_id = var.mongodb_url_secret_name
  labels    = merge(var.labels, { component = "atlas" })

  # NOT `replication { auto {} }`: this org's `constraints/gcp.resourceLocations`
  # policy restricts resources to us-central1/us-east4 only, and automatic
  # replication picks Google-chosen (often out-of-policy) locations — confirmed
  # by hitting this directly when bootstrapping the Atlas key placeholder
  # secrets by hand. User-managed, pinned to gcp_region, stays in-policy.
  replication {
    user_managed {
      replicas {
        location = var.gcp_region
      }
    }
  }
}

resource "google_secret_manager_secret_version" "mongodb_url" {
  secret = google_secret_manager_secret.mongodb_url.id
  # NOTE: connection_strings is a single nested object on this resource (not
  # a list/set, despite how some docs/prose describe it) — confirmed against
  # the actual installed provider schema (mongodb/mongodbatlas v2.16.0) via
  # `terraform providers schema -json` after `connection_strings[0].std...`
  # failed `terraform validate` with "not a collection value".
  secret_data = format(
    "%s/%s?retryWrites=true&w=majority",
    replace(
      mongodbatlas_advanced_cluster.this.connection_strings.standard_srv,
      "mongodb+srv://",
      "mongodb+srv://${mongodbatlas_database_user.app.username}:${random_password.app_db_user.result}@"
    ),
    var.app_database_name
  )
}
